services:
  db:
    image: postgres:16
    container_name: postgres-bakubin
    restart: always
    environment:
      POSTGRES_USER: bakubin-admin
      POSTGRES_PASSWORD: bakubin-admin-Uno.2345678
      POSTGRES_DB: bakubin-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
